version: "3"

services:
  client:
    image: node:lts-buster-slim
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
    command: sh -c "yarn dev"
    working_dir: /client

  server:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./server:/server

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    env_file: server/.env
    volumes:
      - ./server/tmp/db/data:/var/lib/mysql
